### ISSUE TITLE
Take stock of all algorithms

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/liboqs#892]
This issue to capture what we discussed today (also for the benefit of @christianpaquin): 

- Create a current view as to where we stand for each algorithm (round3 readiness, code level, etc.)
- Decide whether/how to parcel out work to arrive at 0.5 release readiness (incl. whether/how to address common code issues as per #849).
- Probably also list release-criteria for 0.5 (not discussed today but in a previous meeting).

@dstebila @xvzcf are working on this.

**Comment by dstebila** [comment]
Here is a draft of a YML file showing the information to be collected about an algorithm and its implementations.

```yaml
name: FrodoKEM
type: kem
principal-submitters:
  - Michael Naehrig
  - Erdem Alkim
  - Joppe Bos
  - Léo Ducas
  - Karen Easterbrook
  - Brian LaMacchia
  - Patrick Longa
  - Ilya Mironov
  - Valeria Nikolaenko
  - Christopher Peikert
  - Ananth Raghunathan
  - Douglas Stebila
auxiliary-submitters: []
crypto_assumption: learning with errors (LWE)
website: https://frodokem.org/
nist-round: 3
variants:
  - name: FrodoKEM-640-AES
    claimed-nist-level: 1
    claimed-security: IND-CCA2
    length-public-key: 9616
    length-ciphertext: 9720
    length-secret-key: 19888
    length-shared-secret: 16
    supported_configurations:
      - 
        platforms: [Linux x86, macOS x86, Windows x86]
        builds:
          - build: portable
            comments: portable C with optional use of AVX2 and AESNI instructions (selected at compile-time, enabled by default if available)
            cpu_features: [AVX2, AESNI]
            common_crypto:
              - AES: liboqs
              - SHA2: liboqs
            implementation: based on https://github.com/microsoft/PQCrypto-LWEKE/commit/669522db63850fa64d1a24a47e138e80a59349db optimized implementation
            no_secret_dependent_branching_claimed: true
            no_secret_dependent_branching_checked_by_valgrind: true
            large_stack_usage: false (this is where we might say an algorithm has large stack usage and may cause failures when run in threads)
          - build: non-portable with AVX2 and AESNI
            comments: portable C with use of AVX2 and AESNI instructions
            cpu_features: [AVX2, AESNI]
            common_crypto:
              - AES: liboqs
              - SHA2: liboqs
            implementation: based on https://github.com/microsoft/PQCrypto-LWEKE/commit/669522db63850fa64d1a24a47e138e80a59349db optimized implementation
            no_secret_dependent_branching_claimed: true
            no_secret_dependent_branching_checked_by_valgrind: true
            large_stack_usage: false
          - build: non-portable without AVX2 or AESNI
            comments: portable C
            cpu_features: [AVX2, AESNI]
            common_crypto:
              - AES: liboqs
              - SHA2: liboqs
            implementation: based on https://github.com/microsoft/PQCrypto-LWEKE/commit/669522db63850fa64d1a24a47e138e80a59349db optimized implementation
            no_secret_dependent_branching_claimed: true
            no_secret_dependent_branching_checked_by_valgrind: true
            large_stack_usage: false
      - 
        platforms: [Linux ARM]
        builds:
          - build: all
            comments: portable C
            cpu_features: []
            common_crypto:
              - AES: liboqs
              - SHA2: liboqs
            implementation: based on https://github.com/microsoft/PQCrypto-LWEKE/commit/669522db63850fa64d1a24a47e138e80a59349db optimized implementation
            no_secret_dependent_branching_claimed: true
            no_secret_dependent_branching_checked_by_valgrind: true
            large_stack_usage: false
```

**Comment by baentsch** [comment]
Thanks for this first cut. First questions:
1) What defines `large_stack_usage`? Shouldn't this better be an "evaluated" constant (e.g., LARGE, MEDIUM, SMALL) based on some concrete measurements? What about heap requirements?
2) Has this been built/extended from https://github.com/PQClean/PQClean/blob/master/crypto_kem/frodokem1344aes/META.yml ? Then there'd be a quick path forward to completion for all algorithms (at least for PQClean-originating algorithms)
3) Is a number for `nist-round` sufficient? How do you distinguish between "Finalists" and "Alternate Candidates"?

**Comment by dstebila** [comment]
> 1. What defines `large_stack_usage`? Shouldn't this better be an "evaluated" constant (e.g., LARGE, MEDIUM, SMALL) based on some concrete measurements? What about heap requirements?

The concrete requirement here was "have we observed it crashing in multi-threaded tests in the language wrappers"?

> 2. Has this been built/extended from https://github.com/PQClean/PQClean/blob/master/crypto_kem/frodokem1344aes/META.yml ? Then there'd be a quick path forward to completion for all algorithms (at least for PQClean-originating algorithms)

Not systematically, just inspired by.

> 3. Is a number for `nist-round` sufficient? How do you distinguish between "Finalists" and "Alternate Candidates"?

This was intended to keep track that we've updated to the Round 3 version.

**Comment by dstebila** [comment]
Tagging @xvzcf @christianpaquin @crockeea @jschanck @bhess @vsoftco @baentsch to invite any feedback.

**Comment by baentsch** [comment]
Beyond the already answered questions above, do we safely assume that each algorithm is using common RAND? Should we have a test to validate that? 

Looking at other common code, is it correct that Frodo unlike other algorithms doesn't use SHA3 (incl. SHA3x4)? Last question: Do we agree that the `common_crypto` tag also addresses/resolves #849?

If so, I'd support using/filling this template for all algorithms (and release 0.5 when all algs have the `nist_round` tagged 3).

**Comment by bhess** [comment]
Looks very good.

Is the goal to use these files also for a direct upstream-import of the implementations? If so it can make sense to unify some of the structure and naming (e.g. "implementations" vs. "supported_configurations", the way to encode the supported platforms). Compare for example here: https://github.com/pq-crystals/dilithium/blob/master/Dilithium2_META.yml

Additional information that can be useful:

- KAT hashes
- Compile options used, if any
- Quantified stack usage (probably needs additional profiling with Valgrind/massif or similar)
- Heap usage


> ```yaml
>  supported_configurations:
>       - 
>         platforms: [Linux x86, macOS x86, Windows x86]
> ```

Is it x86 or x86_64?


> ```yaml
>       - 
>         platforms: [Linux ARM]
> ```

Similar here, do we want to detail the ARM architecture (aarch64, armhf, armel, ..)?

**Comment by dstebila** [comment]
> Beyond the already answered questions above, do we safely assume that each algorithm is using common RAND? Should we have a test to validate that?

I hadn't thought to check if people are using something other than common RAND.  I'm not aware of anyone doing that in the algorithms we have.  Not sure how we'd validate that automatically though.

> Looking at other common code, is it correct that Frodo unlike other algorithms doesn't use SHA3 (incl. SHA3x4)? Last question: Do we agree that the `common_crypto` tag also addresses/resolves #849?

Oops, all Frodo variants do use SHA3, not SHA2; the -SHAKE variants just use it more.  Will have to fix.  And yes, hopefully this will resolve #849.

**Comment by dstebila** [comment]
> Is the goal to use these files also for a direct upstream-import of the implementations? 

The initial goal was to provide an organized summary of the implementations characteristics, for people to understand what we have and to generate relevant documentation/tables.  It was not an immediate goal to tie in with the copy-from-upstream mechanism; I was worried that expanding the scope too far would mean it never gets done.

> Additional information that can be useful:
> 
> * KAT hashes

Okay if we imagine this to be used for automatically connecting with code; less necessary if we imagine this is oriented around documentation (since those KATs are already present in the same commit elsewhere in the liboqs repo).

> * Compile options used, if any

Specifically?

> * Quantified stack usage (probably needs additional profiling with Valgrind/massif or similar)
> * Heap usage

To me that's more of an output characteristic, something that would e.g. be measured using profiling, rather than reported on a specification document like this one.

> >         platforms: [Linux x86, macOS x86, Windows x86]
> Is it x86 or x86_64?
> >         platforms: [Linux ARM]
> Similar here, do we want to detail the ARM architecture (aarch64, armhf, armel, ..)?

Yes, that is a good point.

**Comment by baentsch** [comment]
> To me that's more of an output characteristic, something that would e.g. be measured using profiling, rather than reported on a specification document like this one.

+1. Also, such properties are compiler&platform dependent. @bhess If you're not aware of it, you may want to head over to https://openquantumsafe.org/benchmarking/visualization/mem_sig_series.html (where you can --among many other options-- toggle between maxHeap and maxStack usage comparisons) to take a look at what we already have. Suggestions for improvements always welcome. Oh, and

> Compile options used, if any

are also captured there.

**Comment by bhess** [comment]
Thanks @dstebila @baentsch for the details. Makes a lot of sense for documentation. Having the output characteristics and used settings available in the profiling page is better than putting them in static docs.

**Comment by xvzcf** [comment]
What about changing the `supported_configurations` key to `build_configurations` and having it be defined something like:

```yaml
build_configurations:
  x86-64:
    - 
      type: portable
      comments: portable C with optional use of AVX2 and AESNI instructions (selected at compile-time, enabled by default if available)
      platforms: [Linux, macOS, Windows]
      cpu_features: [AVX2, AESNI]
      common_crypto:
         - AES: liboqs
         - SHA2: liboqs
      implementation: based on https://github.com/microsoft/PQCrypto-LWEKE/commit/669522db63850fa64d1a24a47e138e80a59349db optimized implementation
      no_secret_dependent_branching_claimed: true
      no_secret_dependent_branching_checked_by_valgrind: true
      large_stack_usage: false (this is where we might say an algorithm has large stack usage and may cause failures when run in threads)
    -
      type: non-portable with AVX2 and AESNI
      comments: non-portable C with use of AVX2 and AESNI instructions
      cpu_features: [AVX2, AESNI]
      platforms: [Linux, macOS, Windows]
      common_crypto:
                - AES: liboqs
                - SHA2: liboqs
      implementation: based on https://github.com/microsoft/PQCrypto-LWEKE/commit/669522db63850fa64d1a24a47e138e80a59349db optimized implementation
      no_secret_dependent_branching_claimed: true
      no_secret_dependent_branching_checked_by_valgrind: true
      large_stack_usage: false
  armhf:
  -
      type: portable
      platforms: [Linux]
      comments: portable C
      cpu_features: []
      common_crypto:
         - AES: liboqs
         - SHA2: liboqs
      implementation: based on https://github.com/microsoft/PQCrypto-LWEKE/commit/669522db63850fa64d1a24a47e138e80a59349db optimized implementation
      no_secret_dependent_branching_claimed: true
      no_secret_dependent_branching_checked_by_valgrind: true
      large_stack_usage: false
  armel:
  ....
```

**Comment by dstebila** [comment]
That seems fine to me, @xvzcf.

**Comment by baentsch** [comment]
Last remaining issue before releasing 0.6, right? Would it be an idea to complete a release of liboqs and all subprojects before the end of May/PQC workshop? For 0.5 it took us a month to move from RC on liboqs until final release of all subprojects... Thus, what about focusing on/closing this now and having a liboqs-0.6 RC by the end of April?

**Comment by dstebila** [comment]
Greed. @xvzcf have you made any progress on generating documentation from the sample YML file?

**Comment by xvzcf** [comment]
Here's the slightly reworked YAML:

```yaml
name: FrodoKEM
type: kem
principal-submitters:
  - Michael Naehrig
  - Erdem Alkim
  - Joppe Bos
  - Léo Ducas
  - Karen Easterbrook
  - Brian LaMacchia
  - Patrick Longa
  - Ilya Mironov
  - Valeria Nikolaenko
  - Christopher Peikert
  - Ananth Raghunathan
  - Douglas Stebila
auxiliary-submitters: []
crypto-assumption: learning with errors (LWE)
website: https://frodokem.org/
nist-round: 3
spec-version: NIST Round 3 submission
spdx-license-identifier: MIT
implementation-chain:
  - SAMPLE_URL_LEAF
  - SAMPLE_URL_INT
  - https://github.com/microsoft/PQCrypto-LWEKE/commit/669522db63850fa64d1a24a47e138e80a59349db
parameter-sets:
  -
    name: FrodoKEM-640-AES
    claimed-nist-level: 1
    claimed-security: IND-CCA2
    length-public-key: 9616
    length-ciphertext: 9720
    length-secret-key: 19888
    length-shared-secret: 16
    implementations:
      -
        arch: x86-64
        portable: yes
        platforms: [Linux, macOS, Windows]
        cpu-extensions-used: [AVX2, AESNI]
        common-crypto:
          - AES: liboqs
          - SHA2: liboqs
        no-secret-dependent-branching-claimed: true
        no-secret-dependent-branching-checked-by-valgrind: true
        large-stack-usage: false
      -
        arch: armel
        portable: no
        cpu-extensions-used: []
        platforms: [Linux, macOS, Windows]
        common-crypto:
          - AES: liboqs
          - SHA2: liboqs
        no-secret-dependent-branching-claimed: true
        no-secret-dependent-branching-checked-by-valgrind: true
        large-stack-usage: false
      -
        arch: armhf
        portable: yes
        platforms: [Linux]
        cpu-extensions-used: []
        common-crypto:
          - AES: liboqs
          - SHA2: liboqs
        no-secret-dependent-branching-claimed: true
        no-secret-dependent-branching-checked-by-valgrind: true
        large-stack-usage: false
```

------------------------------

and the associated documentation markdown:

# FrodoKEM

- **Algorithm type**: key encapsulation mechanism
- **Main cryptographic assumption**: learning with errors (LWE).
- **Authors website**: https://frodokem.org/.
- **Specification version**: NIST Round 3 submission.
- **Implementation taken from**
  - SAMPLE_URL_LEAF, which takes it from
  - SAMPLE_URL_INT, which takes it from
  - https://github.com/microsoft/PQCrypto-LWEKE/commit/669522db63850fa64d1a24a47e138e80a59349db
- **License (SPDX-Identifier)**: MIT.

## Parameter set summary

|  Parameter set   | Security Model   |   Claimed NIST Level |   Public key size (bytes) |   Secret key size (bytes) |   Ciphertext size (bytes) |   Shared secret size (bytes) |
|:----------------:|:-----------------|---------------------:|--------------------------:|--------------------------:|--------------------------:|-----------------------------:|
| FrodoKEM-640-AES | IND-CCA2         |                    1 |                      9616 |                     19888 |                      9720 |                           16 |

## FrodoKEM-640-AES implementation characteristics

|  Architecture  | Platforms            | CPU Extensions Used   | Portable?   | No branching-on-secrets claimed?   | No branching-on-secrets checked by valgrind?   | Large stack usage?   |
|:--------------:|:---------------------|:----------------------|:------------|:-----------------------------------|:-----------------------------------------------|:---------------------|
|     x86-64     | Linux,macOS,Windows, | AVX2,AESNI,           | True        | True                               | True                                           | False                |
|     armel      | Linux,macOS,Windows, |                       | False       | True                               | True                                           | False                |
|     armhf      | Linux,               |                       | True        | True                               | True                                           | False                |

## Explanation of terms

- Large stack usage: INSERT_EXPLANATION_HERE
